on:
  push:
    branches: [master]
  pull_request:
name: Flatpak
jobs:
  flatpak:
    name: Build flatpak from master
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
      with:
        bundle: cz.pervoj.valdo-gtk.master.flatpak
        manifest-path: cz.pervoj.valdo-gtk.json
        cache-key: flatpak-builder-${{ github.sha }}
