on: [push, pull_request]
name: Flatpak
jobs:
  flatpak-builder:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: nahuelwexd/flatpak-builder-action@gnome-3-36
      with:
        manifest-path: cz.pervoj.valdo-gtk.json
        meson-args: -Dprofile=development
        flatpak-module: testproject
        app-id: cz.pervoj.valdo-gtk
        bundle: cz.pervoj.valdo-gtk.flatpak
